---
# Install selinux packages

- name: unwanted packages are removed
  package:
    name: "{{ selinux_packages_remove }}"
    state: absent
  become: true
  when: selinux_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ selinux_packages_repos }}"
    state: "{{ selinux_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ selinux_packages_prereq }}"
    state: "{{ selinux_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ selinux_packages_install }}"
    state: "{{ selinux_packages_state }}"
  become: true
