---
# Template configuration files for selinux

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ selinux_templates_copy }}"
  when: selinux_copy_templates
